import = ["/Users/asiryk/.config/alacritty/riot.toml"]

[shell]
program = "/opt/homebrew/bin/fish"
args = [ "--login" ]

[colors]
draw_bold_text_with_bright_colors = true

[cursor.style]
blinking = "Never"
shape = "Beam"

[cursor.vi_mode_style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.normal]
family = "Hack Nerd Font Mono"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[window]
opacity = 0.9 # Don't use value 1.0 because of the mission control lag on macOS https://github.com/alacritty/alacritty/issues/4410
