# Colors (Riot) - a custom color scheme
[colors.normal]
black         = "#141414" # eerie black
blue          = "#4281a4" # celadon blue
cyan          = "#62bec1" # maximum blue green
green         = "#4d8b31" # maximum green
magenta       = "#aa6292" # pearly purple
red           = "#ca4754" # brick red
white         = "#ecf0f1" # cultured
yellow        = "#e3ae2d" # goldenrod

[colors.primary]
background    = "#191919" # eerie black
