#!/usr/bin/env fish

set -l file $argv[1]
set -l w $argv[2]
set -l h $argv[3]
set -l x $argv[4]
set -l y $argv[5]

set -l mime_type (file --mime-type $file | awk '{print $2}')
set -l mime_encoding (file --mime-encoding $file | awk '{print $2}')

if contains $mime_type image/png image/jpeg image/jpg image/avif
  kitten icat --stdin=no --transfer-mode=memory \
    --place=$w"x"$h"@"$x"x"$y $file </dev/null >/dev/tty

  exit 1
else if test $mime_encoding = "binary"
  echo "[binary] preview disabled"
else
  if test (uname) != Darwin
    set theme TwoDark
  else
    if string match -q "Dark" (defaults read -g AppleInterfaceStyle 2>/dev/null)
      set theme TwoDark
    else
      set theme OneHalfLight
    end
  end

  command bat --color=always --style=numbers --theme=$theme $file
end
