# alias rmd="rm -rf" # the worst alias ever
alias gs="git status -s"
alias ls="ls --color" # Add colorized output to ls
alias ll="ls -lAh"
alias clear="clear -x" # Allow scroll after clear
alias tree="exa --tree"
alias vim="nvim --noplugin"
alias vi="nvim --clean"
alias v="vi"
